name: Actualizar Boletines

on:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 06:00 UTC
  workflow_dispatch:    # Para correr manualmente si quieres

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Para poder pushear cambios luego

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pymupdf

      - name: Ejecutar update_boletines.py
        run: python scripts/update_boletines.py

      - name: Configurar Git para push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detectar cambios y hacer push
        run: |
          if [[ `git status --porcelain` ]]; then
            git add json_chunks/*.jsonl ultima_actualizacion.json
            git commit -m "Actualización automática de boletines y última actualización"
            git push
          else
            echo "No hay cambios para subir."
          fi
