name: Actualizar boletines JSON

on:
  schedule:
    - cron: '0 9 * * *'  # Todos los días a las 9:00 UTC (6:00 AM ARG)
  workflow_dispatch:     # Permite ejecutarlo manualmente desde GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install PyPDF2 requests

      - name: Ejecutar script
        run: python scripts/update_boletines.py

      - name: Subir cambios si los hay
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add json_chunks/boletines_part_*.jsonl
          git diff --cached --quiet || git commit -m "update: nuevo boletín agregado automáticamente"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
