# .github/workflows/update_boletines.yml
name: Actualizar boletines JSON

on:
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install PyMuPDF requests

    - name: Ejecutar script para actualizar boletines
      run: python update_boletines.py

    - name: Subir cambios al repositorio
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add json_chunks/
        git commit -m "Actualización automática de boletines" || echo "Sin cambios"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
