name: Actualizar boletines

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * 1-5'  # Corre de lunes a viernes a las 10:30 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm PyMuPDF

      - name: Ejecutar actualización
        run: python scripts/update_boletines.py

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Actualización automática de boletines"
          git push
        continue-on-error: true
