name: Actualizar boletines

on:
  schedule:
    - cron: '0 8 * * *'  # Todos los días a las 8 AM UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests PyMuPDF

      - name: Ejecutar el script de actualización
        run: python scripts/update_boletines.py

      - name: Confirmar cambios si los hay
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add json_chunks/*.jsonl
          git add public/ultima_actualizacion.json || true
          if git diff --cached --quiet; then
            echo "No hay nuevos boletines para subir."
          else
            git commit -m "Actualización automática de boletines"
            git push
          fi
